"""empty message

Revision ID: 2cc1e5e3d07d
Revises: ccf3e56b44f9
Create Date: 2018-02-15 18:41:49.044247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc1e5e3d07d'
down_revision = 'ccf3e56b44f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('admin_address', sa.String(length=64), nullable=True),
    sa.Column('token_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
