"""empty message

Revision ID: 315113b9a387
Revises: 2cc1e5e3d07d
Create Date: 2018-02-16 02:58:36.732309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315113b9a387'
down_revision = '2cc1e5e3d07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('tokens', sa.Column('modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'modified')
    op.drop_column('tokens', 'created')
    # ### end Alembic commands ###
