name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: docker-compose run ibet-issuer /app/ibet-Issuer/app/tests/qa.sh